"""Strategy / backtest CLI namespace keys (see :mod:`traderbot.algorithms.cli_args`)."""

FAST = "fast"
SLOW = "slow"
SIGNAL = "signal"
PERIOD = "period"
OVERSOLD = "oversold"
OVERBOUGHT = "overbought"
NUM_STD = "num_std"
CONTEXT_BARS = "context_bars"
BUY_MIN_RECENT_RETURN = "buy_min_recent_return"
SELL_MAX_RECENT_RETURN = "sell_max_recent_return"
PRICE_CONFIRM = "price_confirm"
BUY_MIN_FINE_LAST_5M = "buy_min_fine_last_5m"
SELL_MAX_FINE_LAST_5M = "sell_max_fine_last_5m"
VECTORBT = "vectorbt"
VISUALIZE = "visualize"
NO_VISUALIZE = "no_visualize"
NO_PLOT = "no_plot"
